version: "3"

volumes:
  wpfolder:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/leet/data/site
  wpdata:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/leet/data/db

networks:
  mynetwork:
    driver: bridge

services:

  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    env_file:
      - ./.env
    image: mariadb:my
    restart: always
    networks:
      - mynetwork
    volumes:
      - wpdata:/var/lib/mysql

  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress
    image: wordpress:my
    env_file:
      - ./.env
    depends_on:
      - mariadb
      - redis
    restart: always
    networks:
      - mynetwork
    volumes:
      - wpfolder:/var/www/html/

  nginx:
    container_name: nginx
    build: ./requirements/nginx
    image: nginx:my
    ports:
        - 443:443
    depends_on:
      - wordpress
    restart: always
    networks:
      - mynetwork
    volumes:
      - wpfolder:/var/www/html/
  
  redis:
    container_name: redis
    build: ./requirements/bonus/redis
    image: redis:my
    restart: always
    networks:
      - mynetwork

  adminer:
    container_name: adminer
    build: ./requirements/bonus/adminer
    image: adminer:my
    restart: always
    networks:
      - mynetwork

  showcase:
    container_name: showcase
    build: ./requirements/bonus/showcase
    image: showcase:my
    restart: always
    networks:
      - mynetwork
  
  ftpserver:
    container_name: ftpserver
    build: ./requirements/bonus/ftpserver
    image: ftpserver:my
    depends_on:
      - wordpress
    env_file:
      - ./.env
    restart: always
    networks:
      - mynetwork
    volumes:
      - wpfolder:/var/www/html/

  portainer:
    container_name: portainer
    build:
      context: ./requirements/bonus/portainer
    image: portainer:my
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always
    networks:
      - mynetwork
    

