version: "3"
services:

  mariadb:
    container_name: mariadb-live
    build: ./mariadb
    tty: true

  wordpress-like:
    container_name: my-wordpress
    build: ./wordpress-like
    ports:
      - "9000:9000"
    depends_on:
      - mariadb
    tty: true
    volumes:
      - myapp:/var/www/html/

  another-debian:
    container_name: another-nginx
    build: ./another-nginx
    ports:
        - "443:443"
    depends_on:
      - wordpress-like
    tty: true
    volumes:
      - myapp:/var/www/html/
  
  redis:
    container_name: redis-cache
    build: ./redis-cache
    depends_on:
      - wordpress-like
    ports:
      - "6379"
    tty: true

  adminer:
    container_name: my-adminer
    build: ./adminer
    ports:
      - "9999"
    tty: true

  showcase:
    container_name: my-showcase
    build: ./showcase
    ports:
      - "2023"
    tty: true
  
  ftpserver:
    container_name: my-ftpserver
    build: ./ftpserver
    depends_on:
      - wordpress-like
    ports:
      - "21"
    tty: true
    volumes:
      - myapp:/var/www/html/

  # portainer:
  #   container_name: my-portainer
  #   image: portainer/portainer-ce
  #   depends_on:
  #     - wordpress-like
  #   ports:
  #     - "9443:9443"
  #   tty: true
  #   volumes:
  #     - /var/run/docker.sock:/var/run/docker.sock
  #     - portainer_data:/data

  another:
    container_name: my-another-portainer
    build:
      context: ./portainer
      args:
        - PORTAINER_PASS=${PORTAINER_PASS:-def}
    image: portainer:my
    ports:
      - "9443:9443"
    tty: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
volumes:
  myapp:
  portainer_data:
