version: "3"

volumes:
  wpfolder:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /var/www/html

networks:
  mynetwork:
    driver: bridge

services:

  mariadb:
    container_name: mariadb-live
    build: ./mariadb
    restart: always
    networks:
      - mynetwork

  wordpress-like:
    container_name: my-wordpress
    build: ./wordpress-like
    ports:
      - "9000:9000"
    depends_on:
      - mariadb
    restart: always
    networks:
      - mynetwork
    volumes:
      - wpfolder:/var/www/html/

  another-debian:
    container_name: another-nginx
    build: ./another-nginx
    ports:
        - "443:443"
    depends_on:
      - wordpress-like
    restart: always
    networks:
      - mynetwork
    volumes:
      - wpfolder:/var/www/html/
  
  redis:
    container_name: redis-cache
    build: ./redis-cache
    depends_on:
      - wordpress-like
    ports:
      - "6379"
    restart: always
    networks:
      - mynetwork

  adminer:
    container_name: my-adminer
    build: ./adminer
    ports:
      - "9999"
    restart: always
    networks:
      - mynetwork

  showcase:
    container_name: my-showcase
    build: ./showcase
    ports:
      - "2023"
    restart: always
    networks:
      - mynetwork
  
  ftpserver:
    container_name: my-ftpserver
    build: ./ftpserver
    depends_on:
      - wordpress-like
    ports:
      - "21" 
    restart: always
    networks:
      - mynetwork
    volumes:
      - wpfolder:/var/www/html/

  another:
    container_name: my-another-portainer
    build:
      context: ./portainer
    image: portainer:my
    ports:
      - "9443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always
    networks:
      - mynetwork
    

